services:
  _defaults:
    autowire:      true
    autoconfigure: true
    public:        true
    bind:
      $host: '%pumukit_opencast.host%'
      $username: '%pumukit_opencast.username%'
      $password: '%pumukit_opencast.password%'
      $adminUrl: '%pumukit_opencast.admin_host%'
      $opencastShowImporterTab: '%pumukit_opencast.show_importer_tab%'
      $opencastBatchImportInverted: '%pumukit_opencast.batchimport_inverted%'
      $secondsToSleep: '%pumukit_opencast.seconds_to_sleep_on_commands%'
      $opencastDeleteArchiveMediaPackage: '%pumukit_opencast.delete_archive_mediapackage%'
      $otherLocales: '%pumukit.locales%'
      $defaultTagImported: '%pumukit_opencast.default_tag_imported%'
      $customLanguages: '%pumukit.customlanguages%'
      $template: '%pumukit_notification.template%'
      $player: '%pumukit_opencast.player%'
      $scheduler: '%pumukit_opencast.scheduler%'
      $dashboard: '%pumukit_opencast.dashboard%'
      $deleteArchiveMediaPackage: '%pumukit_opencast.delete_archive_mediapackage%'
      $deletionWorkflowName: '%pumukit_opencast.deletion_workflow_name%'
      $manageOpencastUsers: '%pumukit_opencast.manage_opencast_users%'
      $insecure: '%pumukit_opencast.insecure%'
      $sbsConfiguration: '%pumukit_opencast.sbs%'
      $urlMapping: '%pumukit_opencast.url_mapping%'
      $defaultVars: '%pumukit_opencast.default_vars%'
      $errorIfFileNotExist: '%pumukit_opencast.error_if_file_not_exist%'
      $notificationConfig: '%pumukit_opencast.notifications%'
      $locale: '%kernel.default_locale%'

  Pumukit\OpencastBundle\Controller\:
    resource: '../../Controller/'
    tags: ['controller.service_arguments']

  Pumukit\OpencastBundle\Command\:
    resource: '../../Command/'
    tags: ['console.command']

  Pumukit\OpencastBundle\Services\ClientService:
    class: Pumukit\OpencastBundle\Services\ClientService

  Pumukit\OpencastBundle\Services\OpencastService:
    class: Pumukit\OpencastBundle\Services\OpencastService

  Pumukit\OpencastBundle\Services\SeriesImportService:
    class: Pumukit\OpencastBundle\Services\SeriesImportService

  Pumukit\OpencastBundle\Services\OpencastImportService:
    class: Pumukit\OpencastBundle\Services\OpencastImportService

  Pumukit\OpencastBundle\EventListener\RemoveListener:
    class: Pumukit\OpencastBundle\EventListener\RemoveListener
    tags:
      - { name: "kernel.event_listener", event: "multimediaobject.delete", method: "onMultimediaObjectDelete"}

  Pumukit\OpencastBundle\EventListener\UserListener:
    class: Pumukit\OpencastBundle\EventListener\UserListener
    tags:
      - { name: "kernel.event_listener", event: "user.create", method: "onUserCreate"}
      - { name: "kernel.event_listener", event: "user.update", method: "onUserUpdate"}
      - { name: "kernel.event_listener", event: "user.delete", method: "onUserDelete"}

  Pumukit\OpencastBundle\Services\NotificationService:
    class: Pumukit\OpencastBundle\Services\NotificationService

  Pumukit\OpencastBundle\Services\SeriesSyncService:
    class: Pumukit\OpencastBundle\Services\SeriesSyncService

  Pumukit\OpencastBundle\Services\WorkflowService:
    class: Pumukit\OpencastBundle\Services\WorkflowService

  Pumukit\OpencastBundle\Command\OpencastDeleteEmptyPersonalSeriesCommand:
    class: Pumukit\OpencastBundle\Command\OpencastDeleteEmptyPersonalSeriesCommand
